### ISSUE TITLE
Multiple problems with generating boosters

### ISSUE THREAD

**Issue by Blarfursnarg** [MagicTheGathering/mtg-api#1]
Thank you for providing a great and free resource for MTG developers! Everything is working great for me, except for the /sets/(set)/booster endpoint.

1. Some sets return an internal server error. E.g.: Journey into Nyx (JOU) or Gatecrash (GTC)
    * https://api.magicthegathering.io/v1/sets/gtc/booster
    * https://api.magicthegathering.io/v1/sets/jou/booster
2. Sets that do work return the same card for each rarity. E.g.: Khans of Tarkir (KTK) or Oath of the Gatewatch (OGW)
    * https://api.magicthegathering.io/v1/sets/ktk/booster  
      Gives me 1 mythic rare, 3 times the same uncommon, 10 times the same common, and 1 land.

**Comment by adback03** [comment]
@Blarfursnarg Thanks for the heads up! I will take a look at this later today and see what the issue is.

**Comment by adback03** [comment]
Resolved these issues in d04fc0c. **v1.8.2** has now been released. Please let me know if you experience any other difficulties!

**Comment by Blarfursnarg** [comment]
Works perfectly, thanks!

**Comment by gritzley** [comment]
This seems to be happening again for a couple of sets. I can't generate boosters for MID, VOW, STX, and NEO. There might be others aswell. Also worth noting, NEO and STX don't give errors, but broken boosters (too few cards)
