### ISSUE TITLE
pageSize Variable is ignored

### ISSUE THREAD

**Issue by vrspectre** [MagicTheGathering/mtg-api#11]
It looks like the max value for page size has been set to 100 in addition to the default. Example url:

https://api.magicthegathering.io/v1/cards?pageSize=500&set=KLD

It only fetches 100 items. However, if set to less than 100 it works appropriately. The documentation says that 1000 is the max.

**Comment by adback03** [comment]
Ahh yes, that's my fault. I had changed it to a max of 100 a few weeks ago and completely forgot to update the docs. I'll get that updated and close this issue once published.

Thanks!
