### ISSUE TITLE
Incorrect multiverse ID

### ISSUE THREAD

**Issue by vrspectre** [MagicTheGathering/mtg-api#12]
At first I thought this might be a data issue with the mtgjson, but it's correct there. But wrong here. The gearhulks are in both MPS and KLD. The ones in MPS show the multiverse ID from the ones in KLD. 

https://api.magicthegathering.io/v1/cards/420588 should be the one from MPS but gives a 404

https://api.magicthegathering.io/v1/cards/417582 is the one from KLD and works fine. 

https://api.magicthegathering.io/v1/cards/?set=MPS shows the cards, but the Cataclysmic Gearhulk has the multiverse id from the KLD, not the MPS. 

http://www.mtgjson.com/json/MPS.json has all the correct information. 

Hope that helps.

**Comment by adback03** [comment]
It looks like this was an issue in mtgjson and has since been corrected: https://github.com/mtgjson/mtgjson/issues/225

I've been waiting to update because the most recent release of mtgjson broke a ton of flip cards (https://github.com/mtgjson/mtgjson/issues/240).

**Comment by adback03** [comment]
These cards have been corrected with the latest release.
