### ISSUE TITLE
No way to get cards at random?

### ISSUE THREAD

**Issue by Ketsuban** [MagicTheGathering/mtg-api#15]
I couldn't find any way to get cards at random, either serverside via a random sort order or clientside via a monotonically-increasing ID which I could randomise. (I couldn't even get just one result—`pagesize=1` seems to be ignored.) I'd like to be able to get a random common, and this API seems to be the only way of accomplishing that.

**Comment by adback03** [comment]
Good idea! I'll try to get an update out later this week to generate a random card. Just an fyi, URL parameters are case sensitive, so it would be `pageSize` instead of `pagesize`.

**Comment by adback03** [comment]
This has been resolved. You can now retrieve cards randomly with the `random` query parameter. Examples below:

1 random card:
`https://api.magicthegathering.io/v1/cards?pageSize=1&random=true`

10 random mythic rares
`https://api.magicthegathering.io/v1/cards?pageSize=10&random=true&rarity=mythic rare`

**Comment by Ketsuban** [comment]
Awesome, thanks very much.
