### ISSUE TITLE
Problem fixed in mtgjson not propagated to API yet

### ISSUE THREAD

**Issue by roesel** [MagicTheGathering/mtg-api#18]
Hello, 

I described a data problem at the mtgjson repository - [issue #288](https://github.com/mtgjson/mtgjson/issues/288) but then found out in their [changelog](http://mtgjson.com/changelog.html) that this has been fixed already. 

I am guessing the fact that this is still not fixed in the API is that the database of it is from before Jan 23. How often is the database behind the API rebuild? 

Thanks

**Comment by adback03** [comment]
Hey, I'll hopefully get this update out tonight. Usually with full set releases, the changes will be pushed to the API withing 24 hours. For minor fixes, I usually wait a few days, as sometimes new issues get introduced. Thanks for the heads up though! I'll close this once the changes have been pushed (probably late tonight).

**Comment by adback03** [comment]
The most recent data has now been published.
