### ISSUE TITLE
Special character don't seem to work

### ISSUE THREAD

**Issue by TheOddler** [MagicTheGathering/mtg-api#2]
When requestion a card with a special character in it's name by name an empty reply is returned.

For instance, when I try to get "Ætherize" by name:

    GET https://api.magicthegathering.io/v1/cards?name=Ætherize

The returned json is:

    {"cards":[]}

Replacing "Æ" with "Ae" or "AE" doesn't work either.

It would be nice if both "Ætherize" and "Aetherize" were supported as names in requests.

**Comment by adback03** [comment]
Resolved these issues with the latest release - **v1.8.5** has now been released. Please let me know if you experience any other difficulties!
