### ISSUE TITLE
Duplicates returned for "Nalathni Dragon" 

### ISSUE THREAD

**Issue by AdamLeBlanc** [MagicTheGathering/mtg-api#20]
Came across this randomly when a co-worker searched "dragon" in our app.

to recreate hit this endpoint:

`https://api.magicthegathering.io/v1/cards?name=Nalathni Dragon`

The card "Nalathni Dragon" get's returned twice from the api if he matches the query. This is mostly a pain, but can be worked around. The issue could be there for other cards, but we haven't seen it.

**Comment by adback03** [comment]
It appears as though there are in fact two versions of this card. One was printed in pDRC and one in pMEI.
