### ISSUE TITLE
Card legalities outdated

### ISSUE THREAD

**Issue by RenanRossiDias** [MagicTheGathering/mtg-api#24]
Greetings!

First of all, congratulations for the great MTG API.

I'm pretty sure card legalities aren't refreshed since this year's beggining, cause in January they've banned cards such as "Gitaxian Probe", "Golgary Grave-Troll", so the legalities for these cards are outdated, additionally some cards still have the "Standard" Legality, even when they were already banned from this game format, as we can see in "Emrakul, the Promised End" and "Reflector Mage". 

Is there a kind of "legality lease time"? If yes, how much time is it?

**Comment by adback03** [comment]
Hey, thanks for pointing this out. Can you post this in the following project?

https://github.com/mtgjson/mtgjson/issues

**Comment by silasary** [comment]
This is tracked by mtgjson/mtgjson#332

**Comment by adback03** [comment]
Closing as this seems to have been addressed by mtgjson.
