### ISSUE TITLE
increase pageSize limit

### ISSUE THREAD

**Issue by Ponicorn** [MagicTheGathering/mtg-api#26]
Hi,
Is there any plan to increase the pageSize limit ? 
it's written in the 1.12.5 that it's temporary but it was 10 months ago.
And if it's a non-temporary change, it may be a good idea to update the doc on the website.
( https://docs.magicthegathering.io/#get-all-cards)

**Comment by adback03** [comment]
I've updated the docs to reflect the max pageSize correctly which is 100.
