### ISSUE TITLE
iOS Client Framework

### ISSUE THREAD

**Issue by mamaral** [MagicTheGathering/mtg-api#3]
I'd be interested in developing a Swift framework so iOS clients could easily consume this API, if that was something you'd be interested in working with me on? I've been looking for another side project to work on, just recently got into MTG from some other developer friends at work, and had some ideas for an app that would need an API like this to consume. Being newish to the game, most of my questions would be related to the game itself, as I'm really only familiar with the newest expansions and wouldn't want to make assumptions about the game as a whole based on that.

What do you think?

**Comment by adback03** [comment]
That would be awesome! As far as development goes, I don't know how much help I could be as I have had very little Swift experience. I could certainly help answer questions about the API and the game itself though. I could create a "mtg-sdk-ios" repository and add you as a developer to it. Let me know what you think, and if you are still interested, I'll create the repo!

**Comment by mamaral** [comment]
Awesome, before I start I'd like to get an idea of what you think would be the design would consist of given the API endpoints that exist? I'm envisioning something like this (based on docs):

The `card` class:

- get all cards paginated
- get a specific card
- search for cards with query params

The `set` class:

 - get all sets
 - get a specific set by code
 - generate a pack

Each class will provide a simple wrapper for the API requests and return native instances of those objects.

Is there any functionality I'm missing? Is there any authentication with the requests, like an API key?

**Comment by adback03** [comment]
Here is the list of the endpoints:

```
/cards
/cards/{multiverseid}
/cards?{params}

/sets
/sets/{setCode}
/sets/{setCode}/booster
/sets?{params}

/types
/supertypes
/subtypes
```

So from what I can tell, you have everything there except for being able to search for a set via its name.

As of right now, no authentication is required for any of the endpoints. I have been toying around with some ideas for future updates that may introduce authenticated endpoints, but there are none right now.

**Comment by mamaral** [comment]
Excellent, sounds like it shouldn't be too much work to get that done. I'm
currently on vacation in Disney but should be able to get it started some
time maybe this week, so if you want to create that repo that'd be great!

**Comment by adback03** [comment]
Created the repo and added you as a collaborator: https://github.com/MagicTheGathering/mtg-sdk-ios

Have a great trip!
