### ISSUE TITLE
Translated data

### ISSUE THREAD

**Issue by julienmonnard** [MagicTheGathering/mtg-api#30]
Hi !
I was wondering if there is any way to get the data in a specific language. Not only the card name in "foreignNames", but also the texts and everything.

For now it seems that the requests made with the multiverseid from a specific language returns "404 - Not found".

Example:
If I try to get [https://api.magicthegathering.io/v1/cards/386616](https://api.magicthegathering.io/v1/cards/386616), in the foreignNames node, I find the multiverseid 387692 for French, but if I try to get https://api.magicthegathering.io/v1/cards/387692, I have a 404.

Any chance we can have the full translated data ?

**Comment by adback03** [comment]
I can look into this, but not even mtgjson.com has the translations available. I could attempt to use language translation services, but I'd be worried about the accuracy. I'll see what I can find though.

**Comment by julienmonnard** [comment]
Yes, I saw that everything is in english, also the Oracle texts on [gatherer.wizards.com](gatherer.wizards.com). But they do show printed texts in other languages, that's why I was hoping to have access to these texts :)

**Comment by lfgcampos** [comment]
The `multiverseid` is the id from Oracle (gatherer.wizards.com). You can use it to go there with `printed=true` and read it from there (no APIs that I know has any language other than English).
ex: http://gatherer.wizards.com/Pages/Card/Details.aspx?printed=true&multiverseid=387423

**Comment by Reid-E** [comment]
This feature now exists, so this issue can probably be closed.

The translated text (where available) is now in the foreignNames field, nested under name, text, flavor and imageUrl.

**Comment by julienmonnard** [comment]
Nice, thanks for this! I have to admit that I didn't come here for a while, it's a good opportunity to try new stuff :-)
