### ISSUE TITLE
MTGJSON v4

### ISSUE THREAD

**Issue by lfgcampos** [MagicTheGathering/mtg-api#34]
Andrew, a new version of mtgjson was released.

Do you have plans to migrate your API to that one?
It seems like v3 (currently in use) will be discontinued.

v4: https://github.com/mtgjson/mtgjson4

**Comment by adback03** [comment]
Yes, the API will switch to using the data provided by v4 of mtgjson. V1 of the API will remain the same (as far as responses go) for backwards compatibility. V2 of the API will introduce some breaking changes.

**Comment by lfgcampos** [comment]
Do you have a date for it?
