### ISSUE TITLE
Special Characters and Exact Name Search - No Results

### ISSUE THREAD

**Issue by Mick-a-nator** [MagicTheGathering/mtg-api#4]
(Related to Issue #2 )

When using exact name search using double quotes, card names with special or non-alphanumeric characters return no results.

For example:
- name=Ætherize works, name="Ætherize" does not.
- name=Gideon returns result with first element with name "Gideon's Phalanx", but name="Gideon's Phalanx" returns nothing
- Tested cards containing '-&!?: All with same result. (Characters encoded for URLs in all cases)

**Comment by adback03** [comment]
Thanks for pointing this out! I should hopefully have time to look at this later today.

**Comment by adback03** [comment]
This should now be resolved. Sample requests:

http://api.magicthegathering.io/v1/cards?name=%22r%26d%27s%20secret%20lair%22
http://api.magicthegathering.io/v1/cards?name=%22%C3%86therize%22

**Comment by Phury** [comment]
Something changed ? It does not work anymore

**Comment by MisanthropicBit** [comment]
@Phury: I think so too. I use `mtg-sdk-python` for a project where a passing test suddenly fails now. In my case, it is for an exact name search for [Death's Duet](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=397632). The constructed API url is [`https://api.magicthegathering.io/v1/cards?name=%22Death%27s+Duet%22`](https://api.magicthegathering.io/v1/cards?name=%22Death%27s%20Duet%22) which returns no results even though the [example from the docs](https://docs.magicthegathering.io/#advancedcards_get_by_name) does for Archangel Avacyn.
