### ISSUE TITLE
Incorrect Oracle text

### ISSUE THREAD

**Issue by Indigenuity** [MagicTheGathering/mtg-api#8]
"text" field for cards does not reflect current oracle text, nor is it consistent.  Compare different printings of Winter Orb.  3 printings reflect current (and original) oracle text, 7 have previous (but not original) oracle text.  Also, every card prior to Kaladesh still shows old token phrasing.  

My apologies if this is not the place to report this.

**Comment by adback03** [comment]
Hey, thanks for the heads up! If you could report this to the guys at mtgjson, that would be great.

https://github.com/mtgjson/mtgjson
