### ISSUE TITLE
Filtering by layout is not working

### ISSUE THREAD

**Issue by dlmorais-13** [MagicTheGathering/mtg-api#9]
Looks like filtering by layout is being ignored.

Example:
URL: https://api.magicthegathering.io/v1/cards?layout=token

**Comment by adback03** [comment]
Thanks for pointing this out. I have just pushed out a fix for this issue. Let me know if you continue to have issues!

**Comment by qdelcourte** [comment]
Hi !
It seems to be ignored again.
No results with this : https://api.magicthegathering.io/v1/cards/?layout=token
